# Generated by Django 4.2.5 on 2023-09-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcopy",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookcopy",
            name="barcode",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.bookcopy",
                to_field="barcode",
            ),
        ),
    ]
